version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bun-app
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
